// assets/constants/icons.js
export const icons = {
    add: require('../assets/icons/add.png'),
    addUser: require('../assets/icons/addUser.png'),
    backArrow: require('../assets/icons/backArrow.png'),
    blindEye: require('../assets/icons/blind-eye.png'),
    bookmark: require('../assets/icons/bookmark.png'),
    bookmarked: require('../assets/icons/bookmarked.png'),
    comment: require('../assets/icons/comment.png'),
    create: require('../assets/icons/create.png'),
    cross: require('../assets/icons/cross.png'),
    deletePrimary: require('../assets/icons/deletePrimary.png'),
    edit: require('../assets/icons/edit.png'),
    gallery: require('../assets/icons/gallery.png'),
    hanger: require('../assets/icons/hanger.png'),
    hashtag: require('../assets/icons/hashtag.png'),
    home: require('../assets/icons/home.png'),
    like: require('../assets/icons/like.png'),
    liked: require('../assets/icons/liked.png'),
    menu: require('../assets/icons/menu.png'),    
    message: require('../assets/icons/message.png'),    
    noImage: require('../assets/icons/noImage.png'),
    notification: require('../assets/icons/notification.png'),
    openEye: require('../assets/icons/open-eye.png'),
    paste: require('../assets/icons/paste.png'),
    profile: require('../assets/icons/profile.png'),
    search: require('../assets/icons/search.png'),
    send: require('../assets/icons/send.png'),
    wardrobe: require('../assets/icons/wardrobe.png'),
    // Add other icons here
};